name: Deploy Documentation Site

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Configure Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install MkDocs dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Build Static Documentation Site
        run: |
          mkdocs build

      - name: Configure Pages Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy static site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
